version: '3.8'

services:
  unifi:
    user: unifi
    image: jacobalberty/unifi:v9.2
    container_name: unifi-controller
    restart: unless-stopped
    ports:
      - "8080:8080"
      - "8443:8443"
      - "3478:3478/udp"
      - "10001:10001/udp"
    environment:
      TZ: "America/New_York"
    volumes:
      - unifi:./data/unifi:rw

volumes:
  unifi:
